apiVersion: v1
kind: Pod
metadata:
  name: pod-chat2desk-01
  labels:
     app: pod-01
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      ports:
        - containerPort: 80